# Generated by Django 5.0.6 on 2024-08-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mgr_no',
            new_name='mgr',
        ),
    ]
